include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SBCPUFloatingCC
SBCPUFloatingCC_FILES = SBCPUFloatingCC.m
SBCPUFloatingCC_FRAMEWORKS = UIKit Foundation
SBCPUFloatingCC_PRIVATE_FRAMEWORKS = ControlCenterServices ControlCenterUIKit
SBCPUFloatingCC_CFLAGS = -fobjc-arc
SBCPUFloatingCC_INSTALL_PATH = /Library/ControlCenter/Bundles
SBCPUFloatingCC_RESOURCE_DIRS = Resources

include $(THEOS_MAKE_PATH)/bundle.mk
